// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0zAIWYWQL7Me4yctIW19GnmnP1HeMVL8',
    appId: '1:415933466676:web:494b97a2bb93572a792261',
    messagingSenderId: '415933466676',
    projectId: 'teste-ad99c',
    authDomain: 'teste-ad99c.firebaseapp.com',
    storageBucket: 'teste-ad99c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbQWdG-S4ItLPRRvKubbjSmhrvXVcmvCI',
    appId: '1:415933466676:android:0610152b1c5a4c1c792261',
    messagingSenderId: '415933466676',
    projectId: 'teste-ad99c',
    storageBucket: 'teste-ad99c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhT0YBEw8K6Kq1F1iCQL6f3T0OdG218Q',
    appId: '1:415933466676:ios:58857bcc577723b6792261',
    messagingSenderId: '415933466676',
    projectId: 'teste-ad99c',
    storageBucket: 'teste-ad99c.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbhT0YBEw8K6Kq1F1iCQL6f3T0OdG218Q',
    appId: '1:415933466676:ios:63c00d5457a17b2a792261',
    messagingSenderId: '415933466676',
    projectId: 'teste-ad99c',
    storageBucket: 'teste-ad99c.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
